#server:
#  port: 8085

spring:
  profiles:
    include:
      - oauth
      - aws

  datasource:
#  ?autoReconnect=true&useUnicode=true&characterEncoding=utf8mb4&serverTimezone=KST
    url: jdbc:mariadb://k5a101.p.ssafy.io:3308/whoyou
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb
#    url: jdbc:mariadb://k5a101.p.ssafy.io:3306/whoyou
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: a101dawit!

  jpa:
    open-in-view: false
    generate-ddl: false
    showSql: false
    hibernate:
      ddl-auto: none

## security switch
#  security:
#    basic:
#      enabled: false

logging:
  level:
    root: Info
    com.status.server : Info
