cloud:
  aws:
    credentials:
      accessKey: AKIATRW2G5U2XB2BS64H
      secretKey: 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
    s3:
      bucket: whoyou-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false